apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

images:
  - name: PROJECT_FRONT/IMAGE           #Needs to be tested
    newName: jouchef/server:2.6.1
  - name: PROJECT_BACK/IMAGE
    newName: jouchef/backend:2.10.3
  - name: PROJECT_WIKISCRIPT/IMAGE
    newName: jouchef/wikiscript:2.9.6