apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: local
resources:
  - ../../base
  - ingress.yaml
patches:
  - path: claim-patch.yaml
  - path: statefulset-patch.yaml
  - path: image-names.yaml          #This has not been tested yet locally