apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: local
resources:
  - ../../base
  - ingress.yaml

images:
  - name: PROJECT_FRONT/IMAGE           
    newName: jouchef/server:2.6.1
  - name: PROJECT_BACK/IMAGE
    newName: jouchef/backend:2.10.3
  - name: PROJECT_WIKISCRIPT/IMAGE
    newName: jouchef/wikiscript:2.9.6

patches:
  - path: claim-patch.yaml
  - path: statefulset-patch.yaml
