apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - projectNamespace.yaml
  - persistentVolumeClaim.yaml
  - service.yaml
  - statefulset.yaml
  - deployment.yaml
  - wikiJob.yaml
  