apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - projectNamespace.yaml
  - persistentVolumeClaim.yaml
  - service.yaml
  - statefulset.yaml
  - deployment.yaml
  - wikiJob.yaml
images:
  - name: PROJECT_FRONT/IMAGE
    newName: jouchef/server:latest
  - name: PROJECT_BACK/IMAGE
    newName: jouchef/backend:latest
  