apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-postgres-stset
  namespace: project
spec:
  serviceName: todo-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgres
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      containers:
        - name: todo-postgres-container
          image: postgres:16-alpine
          ports:
            - name: todo-db
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: todo                 #These are not yet handled properly
            - name: POSTGRES_PASSWORD
              value: secretpassword
            - name: POSTGRES_DB
              value: tododb
          volumeMounts:
            - name: todo-postgres-data-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: todo-postgres-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi