apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki-script
  namespace: project
spec:
  schedule: "1 * * * *"
  successfulJobsHistoryLimit: 1 
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki-script
            image: PROJECT_WIKISCRIPT/IMAGE
            imagePullPolicy: IfNotPresent
          restartPolicy: Never 