name: Release application

on:
  push:
    paths: 
      - '.todo_app/app/**'
      - '.github/workflows/deploy-app.yaml'

env:
  PROJECT_ID: '${{ secrets.GKE_PROJECT }}'            #Saved to Github secrets
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: dwk-registry
  IMAGE: todo-front-image               #This appears in Artifact registry
  SERVICE: server-dep                   #Deployment's name
  SERVICE_PATH: './todo_app/manifests'
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'        #By default this is enabled, but because writing needs to be defined also this needs to be.
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v6   #v6 is currently the latest one

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v3
        with: 
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}   #Saved to Github secrets
          service_account: ${{ secrets.SERVICE_ACCOUNT_MAIL }}                    #Saved to Github secrets

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v3

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Configure Docker'
        run: gcloud --quiet auth configure-docker europe-north1-docker.pkg.dev

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v3'
        with:
          project_id: '${{ env.PROJECT_id }}'                                
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'

      - name : 'Form the image name'
        run: echo "IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        run: docker build --tag $IMAGE_TAG ./todo_app/app/

      - name: Publish
        run: docker push $IMAGE_TAG

      - name: Deploy
        run: |-
          kubectl apply -f admin/gke_manifests/ 
          cd ./todo_app/manifests/overlays/gke
          kustomize edit set image PROJECT_FRONT/IMAGE=$IMAGE_TAG
          kustomize build . | kubectl apply -f -
          NS=$(kubectl get -f ../../base/projectNamespace.yaml -o jsonpath="{.metadata.name}")
          kubectl rollout status deployment $SERVICE -n $NS || (
            echo "------------------------------------------------"
            echo "DEPLOYMENT FAILED - DEBUG INFO:"
            echo "------------------------------------------------"
            echo "1. POD STATUS:"
            kubectl get pods -n $NS
            echo "------------------------------------------------"
            echo "2. POD EVENTS (Why is it failing?):"
            kubectl describe pods -n $NS
            echo "------------------------------------------------"
            echo "3. APP LOGS (If crashing):"
            # Hakee lokit deploymentin perusteella
            kubectl logs deployment/$SERVICE -n $NS --all-containers=true --tail=50
            exit 1
          )   
          kubectl get services -o wide -n $NS
    