apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: server-route
  namespace: project
spec:
  parentRefs:
  - name: shared-gateway
    namespace: shared
  rules:

  - matches:
    - path:
        type: PathPrefix
        value: /todos
    backendRefs:
    - name: backend-svc
      port: 2345

  - matches:
    - path:
        type: PathPrefix
        value: /todo
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: server-svc
      port: 2345

  - matches:
    - path:
        type: PathPrefix
        value: /static
    backendRefs:
    - name: server-svc
      port: 2345
      