apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: backend-health-check
  namespace: project
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /todostest
        portSpecification: USE_SERVING_PORT
  targetRef:
    group: ""
    kind: Service
    name: backend-svc
    