apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: gke
resources:
  - ../../base
  - g-httpRoute.yaml
  - healthcheck.yaml   # Makes sure that google does health checking to the correct address. Default is /

patches:
  - path: deployment_env_patch.yaml